name: Generate RSS Feed

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Script
        run: python generate_feed.py

      - name: Commit Updated Feed File
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add feed.xml
          git diff-index --quiet HEAD || git commit -m "Automated update to feed.xml"
          git push
