name: Publish Plant Dataset Container to Docker Hub
on:
  push:
    branches:
      - main

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compile and Push Container Image Assets
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/plant-matrix-data:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/plant-matrix-data:1.0.0
